name: Continuous Integration, Delivery and Deployment with GitHub Actions and .NET 10

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create SQL Server Container
      run: |
        docker run -d --name sqlserver \
          -e "ACCEPT_EULA=Y" \
          -e "MSSQL_lucasjabur_PASSWORD=19032002" \
          -p "1433:1433" \
          mcr.microsoft.com/mssql/server:2022-latest

        timeout 90s bash -c "until docker exec sqlserver /opt/mssql-tools18/bin/sqlcmd -S localhost -U lucasjabur -P '19032002' -Q 'SELECT 1' -C; do sleep 5; done"

    - name: Create SQL Server Database
      run: docker exec sqlserver /opt/mssql-tools18/bin/sqlcmd -S localhost -U lucasjabur -P '19032002' -Q "IF DB_ID('ASP.NET10') IS NULL CREATE DATABASE [ASP.NET10]" -C

    - name: Checkout Repository Code
      uses: actions/checkout@v4
  
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Setup .NET 10
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
